In [1]:
import numpy as np
import random

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def weight(layer1 , layer2):
    return np.random.rand(layer1, layer2)

def activation(a,w):
    z = np.dot(a,w)
    # z = a @ w
    return sigmoid(z)

In [3]:
def forward(input, layers, weights):
    a = input
    for i in weights:
        a = activation(a,i)
    return a

In [4]:
def back_propagate(self, error):

    for i in reversed(range(len(self.derivatives))):

            # get activation for previous layer
        activations = self.activations[i+1]

            # apply sigmoid derivative function
        delta = error * self._sigmoid_derivative(activations)

            # reshape delta as to have it as a 2d array
        delta_re = delta.reshape(delta.shape[0], -1).T

            # get activations for current layer
        current_activations = self.activations[i]

            # reshape activations as to have them as a 2d column matrix
        current_activations = current_activations.reshape(current_activations.shape[0],-1)

            # save derivative after applying matrix multiplication
        self.derivatives[i] = np.dot(current_activations, delta_re)

            # backpropogate the next error
        error = np.dot(delta, self.weights[i].T)

In [5]:
def gradient_descent(self, learningRate=1):
    for i in range(len(self.weights)):
        weights = self.weights[i]
        derivatives = self.derivatives[i]
        weights += derivatives * learningRate

def _sigmoid_derivative(self, x):
    return x * (1.0 - x)

def _mse(self, target, output):
        return np.average((target - output) ** 2)

In [32]:
input = np.array([[2, 6],[2,1]])
# a = 1

In [35]:
layers = np.array([2,3,3,2])
weights = []
for i in range( len(layers)-1):
    weights.append(weight(layers[i],layers[i+1]))
weights

[array([[0.44842024, 0.24867355, 0.96689901],
        [0.56574952, 0.59921946, 0.1123813 ]]),
 array([[0.68424725, 0.0849189 , 0.13315593],
        [0.26212499, 0.29465291, 0.25901585],
        [0.28965681, 0.0483977 , 0.13986408]]),
 array([[0.51603356, 0.44816455],
        [0.3528994 , 0.29872189],
        [0.01639525, 0.49004018]])]

In [36]:
forward(input, layers, weights)

array([[0.65020681, 0.69671956],
       [0.64418361, 0.68972128]])